{"name":"Local: fix_bug","url":"c:\\Users\\84395\\Documents\\GitHub\\Python-PTIT\\fix_bug.py","tests":[{"id":1688902886600,"input":"8\n10010100010010101","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"c:\\Users\\84395\\Documents\\GitHub\\Python-PTIT\\fix_bug.py","group":"local","local":true}